### ISSUE TITLE
Billing Plans and Billing Agreement - Order Summary goes empty

### ISSUE THREAD

**Issue by rodrigoimenes** [paypal/PayPal-Python-SDK#154] opened 2016-09-06 12:58 UTC
- Mode (Sandbox/Live): Sandbox
- Version of Python used: 2.7.6
- SDK Version: 1.11.7

Hi, im using the billing plan / agreement and i have an issue.

Im creating billing plan following the docs and when i redirect user to approval_url, the order summary (left side of the screen), the order summary is empty. (Only showing the "description" field.)

When i used NVP, order summary was showing the price of the billing and all costs.
But when i tried to use in this SDK, no matter what i do, it goes wrong.

Can someone help me?

**Comment by rodrigoimenes** [comment] 2016-09-06 13:05
* Attached the order summary * 

Parameters for Billing Plan:
{
  "name": "T-Shirt of the Month Club Plan",
  "description": "Template creation.",
  "type": "fixed",
  "payment_definitions": [
    {
      "name": "Regular Payments",
      "type": "REGULAR",
      "frequency": "MONTH",
      "frequency_interval": "2",
      "amount": {
        "value": "100",
        "currency": "USD"
      },
      "cycles": "12",
      "charge_models": [
        {
          "type": "SHIPPING",
          "amount": {
            "value": "10",
            "currency": "USD"
          }
        },
        {
          "type": "TAX",
          "amount": {
            "value": "12",
            "currency": "USD"
          }
        }
      ]
    }
  ],
  "merchant_preferences": {
    "setup_fee": {
      "value": "1",
      "currency": "USD"
    },
    "return_url": "http://www.return.com",
    "cancel_url": "http://www.cancel.com",
    "auto_bill_amount": "YES",
    "initial_fail_amount_action": "CONTINUE",
    "max_fail_attempts": "0"
  }
}



Parameters for Billing Agreement:

{
  "name": "T-Shirt of the Month Club Agreement",
  "description": "Agreement for T-Shirt of the Month Club Plan",
  "start_date": datetime.now()
![paypal](https://cloud.githubusercontent.com/assets/8990835/18274569/6770d3e8-7419-11e6-91f1-271567873e5f.png)
,
  "plan": {
    "id": "P-94458432VR012762KRWBZEUA"
  },
  "payer": {
    "payment_method": "paypal"
  },
  "shipping_address": {
    "line1": "111 First Street",
    "city": "Saratoga",
    "state": "CA",
    "postal_code": "95070",
    "country_code": "US"
  }
}

**Comment by rodrigoimenes** [comment] 2016-09-06 13:13
I wanna show the price, because the user is accepting something that he's not seeing in Paypal.

**Comment by jaypatel512** [comment] 2016-10-17 18:10
Duplicate of https://github.com/paypal/PayPal-PHP-SDK/issues/149

**Closed by jaypatel512** 2016-10-17 18:10 UTC
Labels: question
