### ISSUE TITLE
Webhooks Sandbox question

### ISSUE THREAD

**Issue by Godod** [paypal/PayPal-Python-SDK#141] opened 2016-07-04 14:47 UTC
Please, who can describe, how webhooks works in sandbox?

I have 2 registered webhooks:
![webhook](https://s32.postimg.org/hx32eydz9/Screenshot.png "Webhooks")

with right credentials, but in "Webhooks Events" menu - nothing ;( 
![webhook](https://s31.postimg.org/4lralkb97/Screenshot_1.png "Webhooks Events menu")

I don't receive any webhooks when I pay by PayPal (payment).
In sandbox webhooks work? Thanks

P.S. Url valid. When I'm simulate webhook - all ok.
P.P.S Sorry for my bad English

**Comment by StickerFiend** [comment] 2016-07-06 21:27
I'm having the exact same problem with the sandbox. I create an invoice with Invoice.create and then pay for it at the link that is sent in the email. After that payment is approved, I never receive a webhook request. The webhook simulator works fine and I've checked the configuration(URL & Events) to make sure they're correct.

**Comment by Godod** [comment] 2016-07-14 21:31
@ppmtscory 

Payment:
I'm using the Rest API for create payment. Using intent: "order" to create order and than execute him. When order is execute, I'm using authorization capture with "is_final_capture: true". Or, when something wrong (by my validation), I using authorization capture with "is_final_capture: false" to "freeze" money. Than when I'm looked the order, I'm using authorization capture with "is_final_capture: true". When payment is pending by paypal and than payment state change to complete, I expect the capture complete event.

Billing:
When I'm create the billing agreement and activate, I'm accept the payment in paypal sandbox account . When I cancel agreement in paypal sandbox account I excepting billing subscription cancel webhook.

P.S. Sorry for my bad English

**Comment by ppmtscory** [comment] 2016-07-14 21:38
For payments, are you saying that you don't get the Webhook when you do the authorization and then again when you do the capture?  I tested auth/capture quite a bit this morning and they are all showing for me in sandbox.

As for Billing cancellation, that question of cancelling the agreement within the PayPal account is being tracked over on this [issue](https://github.com/paypal/PayPal-PHP-SDK/issues/591).

**Comment by Godod** [comment] 2016-07-15 05:35
@ppmtscory I've refunded five payments with intent="order". I receive only the subscription suspended webhook:

![image](http://image.prntscr.com/image/19f34998c5bd4d9181321fe34ecd7729.png "Webhook Image")

What I'm doing wrong?

Thank you for Billing cancellation issue

**Comment by ppmtscory** [comment] 2016-07-15 16:08
Are you refunding the payment through the account or via API?  If you're refunding the payment from inside the account, then that's going to be the same issue as the billing agreement cancellation.  If you're refunding via API, then you should be receiving the webhooks just fine.

**Comment by StickerFiend** [comment] 2016-07-15 17:32
Thanks @ppmtscory.

Should I be using IPN rather than webhooks for this flow? I was under the impression that if the PayPal resource(Invoice, Payment, etc.) was created via the PayPal REST API that any event/action on that resource would trigger a hook.

**Comment by ppmtscory** [comment] 2016-07-15 18:05
@StickerFiend for the time being, yes IPN should work for you.  The internal teams are working on enabling the webhooks for 'web' events as well but, unfortunately, I don't have any ETA that I can give out confidently.

**Comment by ppmtscory** [comment] 2016-07-20 16:52
Closing this out in favor of this [issue](https://github.com/paypal/PayPal-PHP-SDK/issues/591).  I'm about to post an update over there.

**Closed by ppmtscory** 2016-07-20 16:52 UTC

**Comment by Godod** [comment] 2016-07-21 09:07
Sorry for late answer, I've refund a payment from sandbox seller account, but webhook doesn't sent. Thank you.

**Comment by ppmtscory** [comment] 2016-07-21 21:21
@Godod no problem, I figured it was the case that you were refunding within the account.  That web event doesn't trigger the webhook currently.  Also, not sure that you'd really need a webhook for that specific event since it's you, the merchant, doing the refund manually you obviously know that the refund took place.  If you needed something to automate systems in your backend, then you'd want to implement the refund via API.

**Comment by Godod** [comment] 2016-07-25 11:36
@ppmtscory Ok. Thank you.

**Comment by Cangoo** [comment] 2017-02-23 12:02
Does the webhook trigger now when refunding within the account? 

> Also, not sure that you'd really need a webhook for that specific event since it's you, the merchant, doing the refund manually you obviously know that the refund took place.

Well when doing the refund with the REST-API, you know as well that you, the merchant, has done the refund and you wouldn't need webhook as well. The problem is that some merchants prefer doing refunds within the account, and the shop-system needs to know that a refund was made.

I was told by the paypal-support that IPNs doesn't work with payments created with the REST-API, so there is no way to get informed when the merchant do the refund within the account?

**Comment by pp-randy** [comment] 2017-03-20 16:56
Sorry for any confusion here. IPNs should still be sent for most things, it is the Webhooks that currently only work REST API.  Currently, In the case of a refund from an account, the IPN would be sent and not the webhook.

**Comment by Cangoo** [comment] 2017-03-21 09:11
Thanks for your reply. Strange enough, I got a PAYMENT.SALE.REFUNDED from a refund we triggered manually in the paypal-backend, so it seems webhooks are not only called for actions triggered via the REST API but in the paypal-Backend as well?!

 

I’m a bit confused now.

 

Regards

 

Martin

**Comment by pp-randy** [comment] 2017-03-21 14:26
Sorry I edited my previous statement yesterday.
