### ISSUE TITLE
Payment.create() 503 error

### ISSUE THREAD

**Issue by minibear0523** [paypal/PayPal-Python-SDK#103] opened 2015-06-24 06:26 UTC
When I create a payment, response status is 503, Internal Error. Does it because in local development environment?

I retry create in command line, 503 again at first, success second time. But in server, response is always 503.

**Comment by avidas** [comment] 2015-06-25 14:23
@minibear0523 do you have any paypal debug ids to provide? You can get them by setting the logging level to DEBUG. It helps us triage the issue.

**Comment by minibear0523** [comment] 2015-06-25 16:09
OK, I paste image for you.
The first image is my django server's http log, it response 500 to web because of payment.create failed.
![qq20150626-1 2x](https://cloud.githubusercontent.com/assets/1175287/8359124/15cc511a-1b97-11e5-95ca-ece228078298.png)

The second image is payment.create response when I using django shell to test api, its status code is 503.
![qq20150626-2 2x](https://cloud.githubusercontent.com/assets/1175287/8359127/16e29794-1b97-11e5-9d5f-eb0823535be6.png)

The third image is my code for create payment in my django server which is very simple, just create a payment and call create function from its caller function.
![qq20150626-3 2x](https://cloud.githubusercontent.com/assets/1175287/8359198/6ffd2722-1b97-11e5-8589-6776b9ee4b7c.png)

**Comment by avidas** [comment] 2015-06-25 17:53
Hey, thanks for providing the detailed logs and the debug id :+1: , the root cause of this seems to be an issue with timeouts in one of the underlying services. We will keep you posted on the updates to this issue.

**Comment by avidas** [comment] 2015-06-25 19:03
Hey, could you also try using a different credit number, perhaps something generated by a tool (e.g. http://www.getcreditcardnumbers.com/ ) to see if the problem persists? This issue sometimes comes up due to overuse of default credit card numbers posted in the docs.

**Comment by avidas** [comment] 2015-06-26 20:27
Are you still receiving those timeouts?

**Comment by avidas** [comment] 2015-06-30 15:55
Closing as this should be fixed, reopen if necessary.

**Closed by avidas** 2015-06-30 15:55 UTC
Labels: api-bug, api-payments

**Comment by exengineer1** [comment] 2020-01-31 06:44
I am facing same problem. Link you provide is not working.

> Hey, could you also try using a different credit number, perhaps something generated by a tool (https://ppmts.custhelp.com/app/answers/detail/a_id/750 should help ) to see if the problem persists? This issue sometimes comes up due to overuse of default credit card numbers posted in the docs.



> Hey, could you also try using a different credit number, perhaps something generated by a tool (https://ppmts.custhelp.com/app/answers/detail/a_id/750 should help ) to see if the problem persists? This issue sometimes comes up due to overuse of default credit card numbers posted in the docs.

**Comment by exengineer1** [comment] 2020-01-31 06:45
I am facing same problem. Link you provide is not working.

> Hey, could you also try using a different credit number, perhaps something generated by a tool (https://ppmts.custhelp.com/app/answers/detail/a_id/750 should help ) to see if the problem persists? This issue sometimes comes up due to overuse of default credit card numbers posted in the docs.
