### ISSUE TITLE
Add timeout (with potential default)

### ISSUE THREAD

**Issue by nh2d** [paypal/PayPal-Python-SDK#246] opened 2018-03-23 19:27 UTC

**Comment by xiaoleih41** [comment] 2018-03-26 14:07
Please provide more detail what the issue is and what do you need help with.

**Comment by nh2d** [comment] 2018-03-27 17:03
https://github.com/paypal/PayPal-Python-SDK/pull/247 Here is a PR for the update. Sorry I did not see your message about details. If the PR is unclear I can go into more detail :) Pretty much just add optional timeout.

**Comment by bluk** [comment] 2018-04-06 15:13
Closing this issue in favor of the PR. Thanks.

**Closed by bluk** 2018-04-06 15:13 UTC
